name: presentation
description: 'Blind presentation package'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  domain:
    path: ../domain
  core_util:
    path: ../core/util
  core_bloc:
    path: ../core/bloc
