name: core_theme
description: 'core theme package'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
