name: core_server
description: 'A server app using the shelf package and Docker'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  args: ^2.7.0
  faker: ^2.2.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_swagger_ui: ^2.0.0

dev_dependencies:
  build_runner: ^2.10.4
  http: ^1.6.0
  json_serializable: ^6.11.3
  lints: ^5.1.1
