name: di
description: 'Blind di package'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation
  core_flutter_bloc:
    path: ../core/flutter_bloc
  core_util:
    path: ../core/util
