name: tool_blind_theme
description: 'tool blind theme package'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  core_theme:
    path: ../../../core/theme

dev_dependencies:
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  assets:
    - assets/colors/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.ttf
          weight: 600
