name: core_util
description: 'core util package'
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: ^4.0.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  shimmer: ^3.0.0
  firebase_core: ^4.2.1
